src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('administrator-will-respond', views.AdministratorWillRespondView.as_view(), name='administrator-will-respond'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(), name='show'),
]

src/users/urls.py
from django.urls import re_path
from django.urls import path, include

"""
    this tag makes all the urls reverse into 'users:{name}'
"""
app_name = 'users'

urlpatterns = [
]

urlpatterns += [
	re_path(r'^select2/', include('django_select2.urls')),
]

src/profiles/models.py
import uuid
from django.db import models
from django.conf import settings


class BaseProfile(models.Model):

    USER_TYPE_VALUES = ('Standard', 'Professional')
    USER_TYPE_TEXTS = ('Standard user – educational purposes only',
                       'Professional user – for use with City of Raleigh design review (requires City approval)')
    USER_TYPE_CHOICES = zip(USER_TYPE_VALUES, USER_TYPE_TEXTS)

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                primary_key=True)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    user_type = models.CharField('User Type', choices=USER_TYPE_CHOICES, max_length=20, null=True, blank=True)
    favoriteDate = models.DateField('Favorite Date', null=True, blank=True)
    picture = models.ImageField('Profile picture',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField("Short Bio", max_length=200, blank=True, null=True)
    email_verified = models.BooleanField("Email verified", default=False)

    class Meta:
        abstract = True


class Profile(BaseProfile):
    def __str__(self):
        return "{}'s profile". format(self.user)

src/profiles/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Field
from crispy_forms.bootstrap import FormActions
from django.contrib.auth import get_user_model

from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False
        self.helper.layout = Layout(
            Field('name'),
            Field('email'),
            Field('phone_tx'),
            Field('organization_tx', placeholder='eg. City of Raleigh, your company name, etc.'),
            Field('job_title'),
        )

    class Meta:
        model = User
        fields = ['name', 'phone_tx', 'job_title', 'organization_tx', 'email', ]


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['user_type'].label = "Desired Level of Tool Use"

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.include_media = False  # this was suggested in https://github.com/benmurden/django-intl-tel-input
        self.helper.layout = Layout(
            Field('bio'),
            Field('user_type'),
            FormActions(
                Submit('save', 'Save changes'),
                HTML('<a class="btn btn-info" href={% url "profiles:show_self" %}>Cancel</a>')
            )
        )

    class Meta:
        model = models.Profile
        fields = ['bio', 'user_type', ]

src/profiles/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    """

    this is the account/profile page accessed via the menu right side dropdown 'Account' option.

    """
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super().get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    """

    this is the Edit Account page accessed via the 'Edit Account' text on the account/profile page.

    """
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super().get(request,
                               user_form=user_form,
                               profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}


{% load bootstrap4 %}       {# import bootstrap4/bootstrap3#}

{% bootstrap_messages %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_css %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Edit Account{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="NONE" %}
{% endblock %}

{% block navbar-custom-right %}
{% include "_navbar-right.html" with active_link="NONE" %}
{% endblock %}

    {% block extra_css %}
<!-- edit_profile block extra_css -->
{{ form.media.js }}
<!-- end edit_profile block extra_css -->
    {% endblock %}

<!-- Benefits of the Django application -->
{% block content %}

<div class="container">
  <h1 class="text-primary">Edit Account</h1>
  <hr>
  <div class="row">
    <!-- left column -->

      
    <!-- edit form column -->
    <div class="col-md-6">

      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-sm pull-right" href="{% url 'accounts:password-change' %}">Change Password</a>
    </div>
  </div>
</div>

{% endblock content %}

        {% block scripts %}
<!-- start block scripts -->
{{ form.media.js }}
<!-- end block scripts -->
        {% endblock scripts %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ block.super }}Account{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="NONE" %}
{% endblock %}

{% block navbar-custom-right %}
{% include "_navbar-right.html" with active_link="NONE" %}
{% endblock %}

{% block content %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-sm">Edit Account</a>
      {% endif %}
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-6">
      <ul class="list-group">
        <li class="list-group-item text-muted">User</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong>Phone:</strong></span> {{ show_user.phone_tx }}</li>

          <li class="list-group-item text-right"><span class="pull-left"><strong>Affiliation:</strong></span> {{ show_user.organization_tx }}</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Job Title:</strong></span> {{ show_user.job_title }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-6">
        <ul class="list-group">
            <li class="list-group-item text-muted">Profile</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Desired Level of Tool Use:</strong></span> {{ show_user.profile.get_user_type_display }}</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Bio:</strong></span> {{ show_user.profile.bio }}</li>
        </ul>

    </div>
  </div>
</div>

{% endblock %}